name: Build and run tests

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  FIRESTORE_EMULATOR_HOST: localhost:8080
  FIRESTORE_PROJECT_ID: project-test

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      firestore:
        image: mtlynch/firestore-emulator:latest
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results  
    
